export { default as Footer } from './Footer'
export { default as Header } from './Header'
export { default as MyCard } from './MyCard'
export { default as Tags } from './Tags'
export { default as Card1 } from './Card1'
export { default as Calculadora } from './Calculadora'